import React,{useEffect,useState} from 'react';
import {AlertTriangle,Save,Settings2,X} from 'lucide-react';
import {api,ApiError} from '../lib/api';
import {useApi} from '../lib/useApi';

interface Field{id:string;field_key:string;label:string;data_type:'text'|'number'|'date'|'boolean'|'choice'|'multi_choice';help_text:string;required:boolean;choices:string[];value:unknown}
export const CustomFieldsPanel:React.FC<{entityType:string;entityId:string;label:string;onClose:()=>void}>=({entityType,entityId,label,onClose})=>{
  const fields=useApi<Field[]>(`/platform/custom-values?entityType=${entityType}&entityId=${entityId}`);const[values,setValues]=useState<Record<string,unknown>>({});const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');
  useEffect(()=>{if(fields.data)setValues(Object.fromEntries(fields.data.map(field=>[field.id,field.value??(field.data_type==='boolean'?false:field.data_type==='multi_choice'?[]:'')])));},[fields.data]);
  const save=async()=>{setBusy(true);setNotice('');try{for(const field of fields.data??[]){if(field.required&&(values[field.id]===''||values[field.id]===null||values[field.id]===undefined))throw new Error(`${field.label} is required`);}await api.post('/platform/custom-values',{entityType,entityId,values:(fields.data??[]).map(field=>({definitionId:field.id,value:field.data_type==='number'?Number(values[field.id]):values[field.id]}))});setNotice('Custom fields saved');fields.reload();}catch(e){setNotice(e instanceof ApiError?e.message:e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" role="dialog" aria-modal="true" aria-label={`Custom fields for ${label}`}><section className="flex max-h-full w-full max-w-xl flex-col overflow-hidden rounded border bg-white shadow-xl"><header className="flex items-center gap-2 bg-blue-900 px-4 py-3 text-white"><Settings2 className="h-4 w-4"/><strong>Custom fields — {label}</strong><button className="ml-auto min-h-11 min-w-11" aria-label="Close custom fields" onClick={onClose}><X className="mx-auto h-5 w-5"/></button></header>{notice&&<div role={notice==='Custom fields saved'?'status':'alert'} className={`flex items-center gap-2 px-4 py-2 font-semibold ${notice==='Custom fields saved'?'bg-emerald-100 text-emerald-900':'bg-red-700 text-white'}`}>{notice!=='Custom fields saved'&&<AlertTriangle className="h-4 w-4"/>}{notice}</div>}<div className="grid gap-3 overflow-auto p-4">{(fields.data??[]).map(field=><label key={field.id}><span className="mb-1 block text-[11px] font-bold text-slate-700">{field.label}{field.required?' *':''}</span>{field.data_type==='boolean'?<input type="checkbox" checked={Boolean(values[field.id])} onChange={e=>setValues({...values,[field.id]:e.target.checked})}/>:field.data_type==='choice'?<select className="erp-input min-h-11 w-full" value={String(values[field.id]??'')} onChange={e=>setValues({...values,[field.id]:e.target.value})}><option value="">Select</option>{field.choices.map(choice=><option key={choice}>{choice}</option>)}</select>:field.data_type==='multi_choice'?<select multiple className="erp-input min-h-24 w-full" value={(values[field.id] as string[])??[]} onChange={e=>setValues({...values,[field.id]:Array.from(e.target.selectedOptions,option=>option.value)})}>{field.choices.map(choice=><option key={choice}>{choice}</option>)}</select>:<input className="erp-input min-h-11 w-full" type={field.data_type==='number'?'number':field.data_type==='date'?'date':'text'} value={String(values[field.id]??'')} onChange={e=>setValues({...values,[field.id]:e.target.value})}/>} {field.help_text&&<span className="mt-1 block text-[10px] text-slate-500">{field.help_text}</span>}</label>)}{!fields.loading&&(fields.data??[]).length===0&&<p className="py-8 text-center text-slate-500">No active custom fields are configured for this record type.</p>}</div><footer className="flex justify-end border-t bg-slate-50 p-3"><button disabled={busy||(fields.data??[]).length===0} className="erp-btn erp-btn-primary min-h-11" onClick={()=>void save()}><Save className="h-4 w-4"/>Save custom fields</button></footer></section></div>;
};
