import {beforeEach,describe,expect,test,vi} from 'vitest';
import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {PlatformStudioView} from './PlatformStudioView';
import {CustomFieldsPanel} from '../components/CustomFieldsPanel';
let writes:Array<{path:string;body:any}>=[];
beforeEach(()=>{writes=[];vi.stubGlobal('fetch',vi.fn(async(url:string,init?:RequestInit)=>{const path=String(url).replace(/^.*\/api/,'');const method=init?.method??'GET';if(method==='POST'){const body=JSON.parse(String(init?.body??'{}'));writes.push({path,body});const response=path==='/platform/integrations'?{id:'c1',name:body.name,token:'lerp_ONE_TIME_SECRET',subscriptions:[]}:{id:'saved',...body};return{ok:true,status:201,headers:new Headers(),text:async()=>JSON.stringify(response)} as Response;}const data:Record<string,unknown>={'/platform/custom-fields':[],'/platform/report-sources':[{key:'trial_balance',label:'Trial balance',columns:[{key:'code',label:'Code',type:'text'},{key:'balance',label:'Balance',type:'number'}]}],'/platform/reports':[],'/platform/integrations':[],'/platform/custom-values?entityType=payment&entityId=p1':[{id:'f1',field_key:'bank_batch',label:'Bank batch',data_type:'text',help_text:'Bank upload reference',required:true,choices:[],value:'B-1'}]};return{ok:true,status:200,headers:new Headers(),text:async()=>JSON.stringify(data[path]??[])} as Response;}));});

describe('shared platform studio',()=>{
  test('publishes a typed custom field from the owner workbench',async()=>{render(<PlatformStudioView/>);fireEvent.change(screen.getByText('Field label').parentElement!.querySelector('input')!,{target:{value:'Buyer segment'}});fireEvent.change(screen.getByPlaceholderText('buyer_segment'),{target:{value:'buyer_segment'}});fireEvent.click(screen.getByRole('button',{name:'Publish field'}));await waitFor(()=>expect(writes.some(w=>w.path==='/platform/custom-fields'&&w.body.fieldKey==='buyer_segment')).toBe(true));});
  test('creates an integration and exposes its secret only in the response',async()=>{render(<PlatformStudioView/>);fireEvent.click(screen.getByRole('button',{name:'Integration feeds'}));fireEvent.change(screen.getByLabelText('Integration name'),{target:{value:'Warehouse bridge'}});fireEvent.click(screen.getByRole('button',{name:'Create feed'}));expect(await screen.findByText('lerp_ONE_TIME_SECRET')).toBeInTheDocument();expect(writes.find(w=>w.path==='/platform/integrations')?.body.subscriptions).toEqual(['sales_invoice.created','payment.created']);});
  test('record panels save shared custom values',async()=>{render(<CustomFieldsPanel entityType="payment" entityId="p1" label="RCPT/1" onClose={()=>{}}/>);const input=await screen.findByDisplayValue('B-1');fireEvent.change(input,{target:{value:'B-2'}});fireEvent.click(screen.getByRole('button',{name:'Save custom fields'}));await waitFor(()=>expect(writes.find(w=>w.path==='/platform/custom-values')?.body.values).toEqual([{definitionId:'f1',value:'B-2'}]));});
});
