import React,{useEffect,useState} from 'react';
import {AlertTriangle,CheckCircle2,Copy,DatabaseZap,FileChartColumn,KeyRound,Power,Plus,Save,Settings2} from 'lucide-react';
import {ToolbarRibbon} from '../components/ToolbarRibbon';
import {api,ApiError} from '../lib/api';
import {useApi} from '../lib/useApi';
import {downloadCsv} from '../lib/csv';

type Tab='fields'|'reports'|'integrations';
interface Field{id:string;entity_type:string;field_key:string;label:string;data_type:string;required:boolean;choices:string[];is_active:boolean}
interface SourceColumn{key:string;label:string;type:string} interface Source{key:string;label:string;columns:SourceColumn[]}
interface Report{id:string;name:string;description:string;source_key:string;columns:string[];filters:Array<{column:string;operator:string;value:string|number}>;sort_spec:{column?:string;direction?:string};is_shared:boolean}
interface Connection{id:string;name:string;adapter:string;description:string;token_prefix:string;is_active:boolean;subscriptions:string[];pending:number}
const input='erp-input min-h-11 w-full';const label='mb-1 block text-[11px] font-bold text-slate-700';
const ENTITIES=[['ledger_account','Ledger accounts'],['piece','Pieces / barcodes'],['grey_purchase_order','Grey purchase orders'],['finish_sales_order','Finish sales orders'],['sales_invoice','Sales invoices'],['purchase_invoice','Purchase invoices'],['payment','Receipts and payments'],['location_transfer','Godown transfers'],['edition_document','Parallel edition documents'],['edition_resource','Edition materials and resources']];

export const PlatformStudioView:React.FC=()=>{
  const[tab,setTab]=useState<Tab>('fields');const[notice,setNotice]=useState<{kind:'ok'|'error';text:string}|null>(null);const[busy,setBusy]=useState(false);
  const fields=useApi<Field[]>('/platform/custom-fields');const sources=useApi<Source[]>('/platform/report-sources');const reports=useApi<Report[]>('/platform/reports');const connections=useApi<Connection[]>('/platform/integrations');
  const run=async(job:()=>Promise<unknown>,message:string)=>{setBusy(true);setNotice(null);try{await job();setNotice({kind:'ok',text:message});fields.reload();reports.reload();connections.reload();}catch(e){setNotice({kind:'error',text:e instanceof ApiError?e.message:String(e)});}finally{setBusy(false);}};
  return <main className="flex h-full flex-col overflow-hidden bg-[#ecf1f7] text-xs text-slate-800"><ToolbarRibbon title="Customization, Reports & Integration Studio" onPrint={()=>window.print()}/>
    {notice&&<div role={notice.kind==='error'?'alert':'status'} className={`flex items-center gap-2 px-4 py-2 font-semibold text-white ${notice.kind==='error'?'bg-red-700':'bg-emerald-700'}`}>{notice.kind==='error'?<AlertTriangle className="h-4 w-4"/>:<CheckCircle2 className="h-4 w-4"/>}{notice.text}</div>}
    <nav aria-label="Platform sections" className="flex flex-wrap gap-2 border-b bg-white p-2">{([['fields','Custom fields',Settings2],['reports','Report builder',FileChartColumn],['integrations','Integration feeds',DatabaseZap]] as const).map(([id,text,Icon])=><button key={id} aria-current={tab===id?'page':undefined} className={`erp-btn min-h-11 ${tab===id?'erp-btn-primary':''}`} onClick={()=>setTab(id)}><Icon className="h-4 w-4"/>{text}</button>)}</nav>
    <div className="flex-1 overflow-auto p-4">{tab==='fields'&&<Fields fields={fields.data??[]} busy={busy} run={run}/>} {tab==='reports'&&<Reports sources={sources.data??[]} reports={reports.data??[]} busy={busy} run={run}/>} {tab==='integrations'&&<Integrations rows={connections.data??[]} busy={busy} run={run}/>}</div>
  </main>;
};

function Fields({fields,busy,run}:{fields:Field[];busy:boolean;run:(job:()=>Promise<unknown>,message:string)=>Promise<void>}){
  const[form,setForm]=useState({entityType:'ledger_account',fieldKey:'',label:'',dataType:'text',helpText:'',required:false,choices:''});
  const save=()=>run(async()=>{await api.post('/platform/custom-fields',{...form,choices:form.choices.split(',').map(x=>x.trim()).filter(Boolean)});setForm({...form,fieldKey:'',label:'',helpText:'',choices:''});},'Custom field published for the selected record type');
  return <div className="mx-auto grid max-w-7xl gap-4 lg:grid-cols-[420px_1fr]"><section className="rounded border bg-white p-4"><h1 className="text-sm font-bold text-blue-950">Define one field, reuse it on every matching record</h1><p className="mt-1 text-slate-600">Keys are permanent API names. Deactivate definitions instead of deleting business data.</p><div className="mt-4 grid gap-3"><label><span className={label}>Record type</span><select className={input} value={form.entityType} onChange={e=>setForm({...form,entityType:e.target.value})}>{ENTITIES.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label><span className={label}>Field label</span><input className={input} value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></label><label><span className={label}>API key</span><input className={`${input} font-mono`} placeholder="buyer_segment" value={form.fieldKey} onChange={e=>setForm({...form,fieldKey:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,'_')})}/></label><label><span className={label}>Type</span><select className={input} value={form.dataType} onChange={e=>setForm({...form,dataType:e.target.value})}>{['text','number','date','boolean','choice','multi_choice'].map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select></label>{['choice','multi_choice'].includes(form.dataType)&&<label><span className={label}>Allowed choices — comma separated</span><input className={input} value={form.choices} onChange={e=>setForm({...form,choices:e.target.value})}/></label>}<label><span className={label}>Help text</span><input className={input} value={form.helpText} onChange={e=>setForm({...form,helpText:e.target.value})}/></label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={form.required} onChange={e=>setForm({...form,required:e.target.checked})}/>Required when entered</label><button disabled={busy||form.label.length<2||form.fieldKey.length<2} className="erp-btn erp-btn-primary min-h-11" onClick={()=>void save()}><Plus className="h-4 w-4"/>Publish field</button></div></section>
    <section className="overflow-hidden rounded border bg-white"><h2 className="border-b bg-slate-50 px-4 py-3 font-bold text-blue-950">Company field catalogue</h2><div className="overflow-auto"><table className="w-full"><thead><tr><th className="p-2 text-left">Record</th><th className="p-2 text-left">Field</th><th className="p-2 text-left">Type</th><th className="p-2">Required</th><th className="p-2">Status</th></tr></thead><tbody>{fields.map(row=><tr className="border-t" key={row.id}><td className="p-2">{ENTITIES.find(x=>x[0]===row.entity_type)?.[1]??row.entity_type}</td><td className="p-2"><strong>{row.label}</strong><span className="block font-mono text-[10px] text-slate-500">{row.field_key}</span></td><td className="p-2">{row.data_type.replace('_',' ')}</td><td className="p-2 text-center">{row.required?'Yes':'—'}</td><td className="p-2 text-center">{row.is_active?'Active':'Inactive'}</td></tr>)}{fields.length===0&&<tr><td colSpan={5} className="p-8 text-center text-slate-500">No custom fields yet.</td></tr>}</tbody></table></div></section></div>;
}

function Reports({sources,reports,busy,run}:{sources:Source[];reports:Report[];busy:boolean;run:(job:()=>Promise<unknown>,message:string)=>Promise<void>}){
  const[sourceKey,setSourceKey]=useState('trial_balance');const source=sources.find(s=>s.key===sourceKey)??sources[0];const[columns,setColumns]=useState<string[]>([]);const[name,setName]=useState('');const[shared,setShared]=useState(false);const[filter,setFilter]=useState({column:'',operator:'contains',value:''});const[selected,setSelected]=useState('');const[rows,setRows]=useState<Record<string,unknown>[]>([]);
  useEffect(()=>{if(source){setColumns(source.columns.map(c=>c.key));setFilter({column:source.columns[0]?.key??'',operator:source.columns[0]?.type==='text'?'contains':'eq',value:''});}},[sourceKey,source]);
  const save=()=>run(()=>api.post('/platform/reports',{name,sourceKey:source?.key,columns,filters:filter.value!==''?[filter]:[],sort:columns[0]?{column:columns[0],direction:'asc'}:undefined,isShared:shared}),'Reusable report saved');
  const execute=async(id:string)=>{setSelected(id);const result=await api.post<{rows:Record<string,unknown>[]}>(`/platform/reports/${id}/run`,{limit:500});setRows(result.rows);};
  const headers=rows[0]?Object.keys(rows[0]):reports.find(r=>r.id===selected)?.columns??[];
  return <div className="mx-auto grid max-w-7xl gap-4 xl:grid-cols-[480px_1fr]"><section className="rounded border bg-white p-4"><h1 className="text-sm font-bold text-blue-950">Safe report builder</h1><p className="mt-1 text-slate-600">Choose from governed data sources. User text is bound as data and never becomes SQL.</p><div className="mt-4 grid gap-3"><label><span className={label}>Data source</span><select aria-label="Report data source" className={input} value={sourceKey} onChange={e=>setSourceKey(e.target.value)}>{sources.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select></label><fieldset><legend className={label}>Visible columns</legend><div className="grid grid-cols-2 gap-1 rounded border p-2">{source?.columns.map(c=><label className="flex min-h-9 items-center gap-2" key={c.key}><input type="checkbox" checked={columns.includes(c.key)} onChange={e=>setColumns(current=>e.target.checked?[...current,c.key]:current.length===1?current:current.filter(x=>x!==c.key))}/>{c.label}</label>)}</div></fieldset><label><span className={label}>Optional filter column</span><select className={input} value={filter.column} onChange={e=>{const c=source?.columns.find(x=>x.key===e.target.value);setFilter({...filter,column:e.target.value,operator:c?.type==='text'?'contains':'eq'});}}>{source?.columns.map(c=><option value={c.key} key={c.key}>{c.label}</option>)}</select></label><div className="grid grid-cols-[140px_1fr] gap-2"><select aria-label="Report filter operator" className={input} value={filter.operator} onChange={e=>setFilter({...filter,operator:e.target.value})}>{(source?.columns.find(c=>c.key===filter.column)?.type==='text'?['contains','eq']:['eq','gte','lte']).map(x=><option key={x} value={x}>{x}</option>)}</select><input aria-label="Report filter value" className={input} placeholder="Leave blank for all rows" value={filter.value} onChange={e=>setFilter({...filter,value:e.target.value})}/></div><label><span className={label}>Report name</span><input aria-label="Custom report name" className={input} value={name} onChange={e=>setName(e.target.value)}/></label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={shared} onChange={e=>setShared(e.target.checked)}/>Share with the whole company</label><button disabled={busy||name.length<2||columns.length===0} className="erp-btn erp-btn-primary min-h-11" onClick={()=>void save()}><Save className="h-4 w-4"/>Save report</button></div></section>
    <section className="overflow-hidden rounded border bg-white"><div className="flex flex-wrap items-center gap-2 border-b bg-slate-50 p-3"><strong className="text-blue-950">Saved report catalogue</strong><select aria-label="Run custom report" className="erp-input ml-auto min-h-11 min-w-56" value={selected} onChange={e=>void execute(e.target.value)}><option value="">Choose and run</option>{reports.map(r=><option key={r.id} value={r.id}>{r.name}{r.is_shared?' · shared':''}</option>)}</select><button disabled={rows.length===0} className="erp-btn min-h-11" onClick={()=>downloadCsv(`${reports.find(r=>r.id===selected)?.name??'custom-report'}.csv`,rows)}><FileChartColumn className="h-4 w-4"/>Export result</button></div><div className="overflow-auto"><table className="w-full"><thead><tr>{headers.map(h=><th className="p-2 text-left" key={h}>{source?.columns.find(c=>c.key===h)?.label??h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr className="border-t" key={i}>{headers.map(h=><td className="p-2" key={h}>{String(row[h]??'')}</td>)}</tr>)}{selected&&rows.length===0&&<tr><td className="p-8 text-center text-slate-500" colSpan={Math.max(1,headers.length)}>The report ran successfully and returned no rows.</td></tr>}</tbody></table></div></section></div>;
}

function Integrations({rows,busy,run}:{rows:Connection[];busy:boolean;run:(job:()=>Promise<unknown>,message:string)=>Promise<void>}){
  const[name,setName]=useState('');const[adapter,setAdapter]=useState('pull_api');const[events,setEvents]=useState('sales_invoice.created,payment.created');const[token,setToken]=useState('');
  const create=()=>run(async()=>{const out=await api.post<Connection&{token:string}>('/platform/integrations',{name,adapter,subscriptions:events.split(',').map(x=>x.trim()).filter(Boolean)});setToken(out.token);setName('');},'Integration feed created; copy the one-time key now');
  const rotate=(id:string)=>run(async()=>{const out=await api.post<{token:string}>(`/platform/integrations/${id}/token`,{});setToken(out.token);},'Integration key rotated; the old key no longer works');
  const toggle=(row:Connection)=>run(()=>api.post(`/platform/integrations/${row.id}`,{name:row.name,adapter:row.adapter,description:row.description,subscriptions:row.subscriptions,isActive:!row.is_active}),row.is_active?'Integration paused; its key and event subscriptions are inactive':'Integration enabled');
  return <div className="mx-auto grid max-w-7xl gap-4 lg:grid-cols-[420px_1fr]"><section className="rounded border bg-white p-4"><h1 className="text-sm font-bold text-blue-950">Audited pull integrations</h1><p className="mt-1 text-slate-600">External adapters poll scoped events and acknowledge each delivery. No connector can make the ERP call arbitrary internal URLs.</p><div className="mt-4 grid gap-3"><label><span className={label}>Connection name</span><input aria-label="Integration name" className={input} value={name} onChange={e=>setName(e.target.value)}/></label><label><span className={label}>Adapter</span><select className={input} value={adapter} onChange={e=>setAdapter(e.target.value)}><option value="pull_api">Pull API</option><option value="tally">Tally adapter</option><option value="file_exchange">File exchange</option><option value="custom">Custom adapter</option></select></label><label><span className={label}>Subscribed events — comma separated</span><textarea aria-label="Integration events" className={`${input} min-h-24 font-mono`} value={events} onChange={e=>setEvents(e.target.value)}/></label><button disabled={busy||name.length<2} className="erp-btn erp-btn-primary min-h-11" onClick={()=>void create()}><Plus className="h-4 w-4"/>Create feed</button>{token&&<div role="status" className="rounded border border-amber-400 bg-amber-50 p-3"><strong className="text-amber-900">One-time integration key</strong><code className="mt-2 block break-all rounded bg-white p-2">{token}</code><button className="erp-btn mt-2 min-h-11" onClick={()=>void navigator.clipboard.writeText(token)}><Copy className="h-4 w-4"/>Copy key</button></div>}</div></section>
    <section className="overflow-hidden rounded border bg-white"><h2 className="border-b bg-slate-50 px-4 py-3 font-bold text-blue-950">Connections and delivery backlog</h2><div className="overflow-auto"><table className="w-full"><thead><tr><th className="p-2 text-left">Connection</th><th className="p-2 text-left">Events</th><th className="p-2 text-right">Pending</th><th className="p-2">Controls</th></tr></thead><tbody>{rows.map(row=><tr className="border-t" key={row.id}><td className="p-2"><strong>{row.name}</strong><span className="block text-[10px] uppercase text-slate-500">{row.adapter.replace('_',' ')} · {row.is_active?'active':'paused'}</span></td><td className="p-2 font-mono text-[10px]">{row.subscriptions.join(', ')||'manual events only'}</td><td className="p-2 text-right font-bold">{row.pending}</td><td className="flex flex-wrap gap-1 p-2"><button className="erp-btn min-h-11" onClick={()=>void rotate(row.id)}><KeyRound className="h-4 w-4"/>Rotate {row.token_prefix}…</button><button className="erp-btn min-h-11" onClick={()=>void toggle(row)}><Power className="h-4 w-4"/>{row.is_active?'Pause':'Enable'}</button></td></tr>)}{rows.length===0&&<tr><td colSpan={4} className="p-8 text-center text-slate-500">No integration connections yet.</td></tr>}</tbody></table></div></section></div>;
}
