/** Five parallel edition packs on the shared audited workflow engine. */
import test from 'node:test';import assert from 'node:assert/strict';
const BASE=process.env.API_BASE??'http://127.0.0.1:4000';let owner='',viewer='',storeToken='',feedKey='',resourceFeedKey='',weavingId='',garmentId='',yarnId='';const D='2026-08-27';
async function api(path:string,o:{method?:string;body?:unknown;token?:string;key?:string}={}){const r=await fetch(`${BASE}/api${path}`,{method:o.method??'GET',headers:{'content-type':'application/json',...(o.token?{authorization:`Bearer ${o.token}`}:{}) ,...(o.key?{'x-erp-integration-key':o.key}:{})},body:o.body===undefined?undefined:JSON.stringify(o.body)});const t=await r.text();return{status:r.status,body:t?JSON.parse(t):null};}
async function login(email:string){return api('/auth/login',{method:'POST',body:{email,password:'changeme'}});}
const create=(edition:string,docType:string,payload:any,token=owner)=>api(`/editions/${edition}/documents`,{method:'POST',token,body:{docType,docDate:D,payload,remarks:'edition test'}});

test('all five parallel editions and forty-six full vertical workflows are discoverable',async()=>{owner=(await login('owner@neelkamal.test')).body.token;viewer=(await login('viewer@neelkamal.test')).body.token;storeToken=(await login('store@neelkamal.test')).body.token;const catalog=await api('/editions/catalog',{token:viewer});assert.equal(catalog.status,200);assert.deepEqual(catalog.body.map((x:any)=>x.key).sort(),['dyeing','exports','garments','logistics','weaving']);assert.equal(catalog.body.reduce((n:number,x:any)=>n+x.workflows.length,0),46);assert.ok(catalog.body.every((x:any)=>x.resourceTypes.length>=3));const status=await api('/editions',{token:owner});assert.equal(status.status,200);assert.equal(status.body.filter((x:any)=>x.is_enabled).length,5);});

test('a viewer cannot create vertical operations and malformed payloads are refused',async()=>{const denied=await create('weaving','loom_plan',{loomNo:'L1'},viewer);assert.equal(denied.status,403);const invalid=await create('exports','shipment',{exportOrderRef:'EO-1'});assert.equal(invalid.status,400);});

test('weaving, dyeing, exports and logistics each create their own numbered document',async()=>{const weaving=await create('weaving','loom_plan',{loomNo:'L-12',quality:'60x60 Cambric',warpCount:60,weftCount:60,reed:72,pick:68,plannedMetres:5000,beamNo:'BM-88',startDate:D,targetDate:'2026-09-15'});assert.equal(weaving.status,201,JSON.stringify(weaving.body));assert.match(weaving.body.doc_no,/^WV\/LP\/26-27\//);weavingId=weaving.body.id;
  const dyeing=await create('dyeing','batch_card',{batchRef:'B-900',quality:'Cambric',shade:'Navy 4',colour:'Navy',machine:'Jet-2',inputKg:440,inputMetres:4200,recipeRef:'R-NV-4',targetDate:'2026-09-05'});assert.equal(dyeing.status,201,JSON.stringify(dyeing.body));assert.match(dyeing.body.doc_no,/^DY\/BC\//);
  const exports=await create('exports','export_order',{buyer:'Atlas Home GmbH',country:'Germany',incoterm:'FOB',currency:'EUR',orderValue:48000,shipmentDate:'2026-10-10',portOfLoading:'Nhava Sheva',portOfDischarge:'Hamburg'});assert.equal(exports.status,201,JSON.stringify(exports.body));assert.match(exports.body.doc_no,/^EX\/EO\//);
  const logistics=await create('logistics','consignment',{lrNo:'LR-7001',consignor:'Neelkamal',consignee:'Atlas Forwarder',origin:'Bhiwandi',destination:'Nhava Sheva',packages:120,weightKg:4600,vehicleNo:'MH04AB1234',driver:'Ramesh Patil',driverMobile:'+919876543210'});assert.equal(logistics.status,201,JSON.stringify(logistics.body));assert.match(logistics.body.doc_no,/^LG\/LR\//);});

test('edition resources, material lines, costing, search and integration share one governed spine',async()=>{const connection=await api('/platform/integrations',{method:'POST',token:owner,body:{name:`Weaving resource feed ${Date.now()}`,adapter:'pull_api',subscriptions:['weaving.resource.created']}});assert.equal(connection.status,201,JSON.stringify(connection.body));resourceFeedKey=connection.body.token;const yarn=await api('/editions/weaving/resources',{method:'POST',token:owner,body:{resourceType:'yarn',code:'YRN-60-CMB',name:'60 count combed yarn',uom:'KGS',openingQty:100,openingValue:50000,payload:{lot:'OPEN-60'},isActive:true}});assert.equal(yarn.status,201,JSON.stringify(yarn.body));yarnId=yarn.body.id;
  const lines=await api(`/editions/weaving/documents/${weavingId}/lines`,{method:'POST',token:owner,body:{lines:[{resourceId:yarnId,lineKind:'consume',description:'Warp and weft yarn',quantity:20,uom:'KGS',ratePaise:50000,amountPaise:1000000,payload:{}},{resourceId:null,lineKind:'labour',description:'Loom labour',quantity:1,uom:'JOB',ratePaise:250000,amountPaise:250000,payload:{}}]}});assert.equal(lines.status,200,JSON.stringify(lines.body));const cost=await api(`/editions/weaving/documents/${weavingId}/lines`,{token:owner});assert.equal(cost.body.costing.material_paise,1000000);assert.equal(cost.body.costing.total_cost_paise,1250000);
  const feed=await api('/integrations/feed',{key:resourceFeedKey});assert.ok(feed.body.rows.some((row:any)=>row.entity_id===yarnId&&row.event_type==='weaving.resource.created'));const search=await api('/global-search?q=YRN-60-CMB',{token:owner});assert.ok(search.body.some((row:any)=>row.id===yarnId&&row.module==='edition_weaving'));});

test('edition lifecycle posts average-cost stock once and retains every accepted transition',async()=>{const skipped=await api(`/editions/weaving/documents/${weavingId}/status`,{method:'POST',token:owner,body:{status:'completed'}});assert.equal(skipped.status,400);assert.match(skipped.body.error,/cannot move from draft to completed/i);for(const status of ['in_progress','held','in_progress','completed']){const moved=await api(`/editions/weaving/documents/${weavingId}/status`,{method:'POST',token:owner,body:{status}});assert.equal(moved.status,200,JSON.stringify(moved.body));}const detail=await api(`/editions/weaving/documents/${weavingId}`,{token:owner});assert.equal(detail.body.document.status,'completed');assert.deepEqual(detail.body.events.filter((x:any)=>x.event==='status_changed').map((x:any)=>x.to_status),['in_progress','held','in_progress','completed']);const stock=await api('/editions/weaving/resources?q=YRN-60-CMB',{token:owner});assert.equal(stock.body[0].quantity,80);assert.equal(stock.body[0].value_paise,4000000);assert.equal(stock.body[0].average_rate_paise,50000);});

test('completion cannot drive an edition material below zero',async()=>{const doc=await create('weaving','beam_issue',{loomNo:'L-14',beamNo:'BM-90',yarnLots:'YRN-60-CMB',issuedKg:90,expectedMetres:4000,weaver:'Internal shed'});assert.equal(doc.status,201);const lines=await api(`/editions/weaving/documents/${doc.body.id}/lines`,{method:'POST',token:owner,body:{lines:[{resourceId:yarnId,lineKind:'issue',description:'Yarn issue beyond balance',quantity:90,uom:'KGS',ratePaise:50000,amountPaise:4500000,payload:{}}]}});assert.equal(lines.status,200);assert.equal((await api(`/editions/weaving/documents/${doc.body.id}/status`,{method:'POST',token:owner,body:{status:'in_progress'}})).status,200);const refused=await api(`/editions/weaving/documents/${doc.body.id}/status`,{method:'POST',token:owner,body:{status:'completed'}});assert.equal(refused.status,400);assert.match(refused.body.error,/insufficient edition stock/i);});

test('configured edition workflows require independent maker-checker approval',async()=>{const config=await api('/editions/config',{method:'POST',token:owner,body:{edition:'weaving',isEnabled:true,config:{approvalWorkflows:['loom_maintenance']}}});assert.equal(config.status,200);const doc=await create('weaving','loom_maintenance',{loomNo:'L-12',maintenanceType:'preventive',stoppedAt:D,hours:2,technician:'Service engineer',partsUsed:'Shuttle and belt',resolution:'Aligned, lubricated and trial-run'},storeToken);assert.equal(doc.status,201,JSON.stringify(doc.body));assert.equal(doc.body.approval_status,'not_submitted');assert.equal((await api(`/editions/weaving/documents/${doc.body.id}/status`,{method:'POST',token:storeToken,body:{status:'in_progress'}})).status,200);const blocked=await api(`/editions/weaving/documents/${doc.body.id}/status`,{method:'POST',token:storeToken,body:{status:'completed'}});assert.equal(blocked.status,400);assert.match(blocked.body.error,/requires independent approval/i);assert.equal((await api(`/editions/weaving/documents/${doc.body.id}/approval/submit`,{method:'POST',token:storeToken,body:{}})).status,200);const approved=await api(`/editions/weaving/documents/${doc.body.id}/approval/decision`,{method:'POST',token:owner,body:{decision:'approved'}});assert.equal(approved.status,200,JSON.stringify(approved.body));assert.equal((await api(`/editions/weaving/documents/${doc.body.id}/status`,{method:'POST',token:storeToken,body:{status:'completed'}})).status,200);await api('/editions/config',{method:'POST',token:owner,body:{edition:'weaving',isEnabled:true,config:{}}});});

test('garment documents publish automatic idempotent integration events',async()=>{const conn=await api('/platform/integrations',{method:'POST',token:owner,body:{name:`Garment feed ${Date.now()}`,adapter:'pull_api',subscriptions:['garments.style.created']}});assert.equal(conn.status,201,JSON.stringify(conn.body));feedKey=conn.body.token;const garment=await create('garments','style',{styleCode:'ST-204',buyer:'Northstar Apparel',season:'SS27',garment:'Women shirt',fabric:'Poplin 40s',colour:'White',sizeRange:'XS-XXL',orderQty:12000});assert.equal(garment.status,201,JSON.stringify(garment.body));garmentId=garment.body.id;const feed=await api('/integrations/feed',{key:feedKey});const row=feed.body.rows.find((x:any)=>x.entity_id===garmentId);assert.equal(row.event_type,'garments.style.created');const ack=await api(`/integrations/feed/${row.id}/ack`,{method:'POST',key:feedKey,body:{status:'delivered'}});assert.equal(ack.status,200);});

test('edition documents are part of tenant-wide linked search',async()=>{const found=await api('/global-search?q=ST-204',{token:owner});assert.equal(found.status,200,JSON.stringify(found.body));const row=found.body.find((x:any)=>x.id===garmentId);assert.ok(row);assert.equal(row.module,'edition_garments');assert.equal(row.filter,row.title);});

test('owners can pause an edition without damaging its existing documents',async()=>{const off=await api('/editions/config',{method:'POST',token:owner,body:{edition:'dyeing',isEnabled:false,config:{reason:'seasonal unit paused'}}});assert.equal(off.status,200);const blocked=await create('dyeing','process_stage',{batchRef:'B-900',stage:'dyeing',temperature:90,durationMinutes:60,chemicals:'Reactive dye 12 kg',operator:'Salim'});assert.equal(blocked.status,400);assert.match(blocked.body.error,/disabled/);const list=await api('/editions/dyeing/documents',{token:owner});assert.ok(list.body.total>=1,'existing dyeing batch must remain visible');const on=await api('/editions/config',{method:'POST',token:owner,body:{edition:'dyeing',isEnabled:true,config:{}}});assert.equal(on.status,200);});
