import test from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import {bootstrapTenant,type BootstrapInput} from '../src/bootstrap-tenant.ts';

const BASE=process.env.API_BASE??'http://127.0.0.1:4000';
const stamp=`${Date.now()}${Math.floor(Math.random()*10000)}`;
const input:BootstrapInput={legalName:`Milestone Two Mills ${stamp}`,gstin:'27CDEFG2345H1Z4',pan:'CDEFG2345H',stateCode:'27',fyStart:'2026-04-01',address1:'Evidence Estate',city:'Bhiwandi',pincode:'421302',email:`books.${stamp}@milestone.example`,ownerName:'Milestone Owner',ownerEmail:`owner.${stamp}@milestone.example`,ownerPassword:'MilestoneOwnerPass123'};
let tenantId='',ownerId='',token='',transferId='',debtorId='';

function db(){return new pg.Client({host:process.env.PGHOST,port:Number(process.env.PGPORT),user:process.env.PGUSER??'postgres',database:process.env.TEST_DB??'linkerp_test'});}
async function api(path:string,options:{method?:string;body?:unknown;token?:string}={}){const response=await fetch(`${BASE}/api${path}`,{method:options.method??'GET',headers:{'content-type':'application/json',...(options.token?{authorization:`Bearer ${options.token}`}:{})},body:options.body===undefined?undefined:JSON.stringify(options.body)});const text=await response.text();return{status:response.status,body:text?JSON.parse(text):null};}

test('prepare a clean company and auditable document',async()=>{const client=db();await client.connect();try{const made=await bootstrapTenant(client,input);tenantId=made.tenantId;ownerId=made.ownerId;}finally{await client.end();}const login=await api('/auth/login',{method:'POST',body:{email:input.ownerEmail,password:input.ownerPassword}});assert.equal(login.status,200,JSON.stringify(login.body));token=login.body.token;const branch=await api('/locations',{method:'POST',token,body:{code:'G2',name:'Second Godown',kind:'godown',address:'Lane 2',stateCode:'27',isDefault:false,isActive:true}});assert.equal(branch.status,201,JSON.stringify(branch.body));const client2=db();await client2.connect();try{const main=await client2.query<{id:string}>('select id from business_location where tenant_id=$1 and is_default',[tenantId]);const transfer=await client2.query<{id:string}>(`insert into location_transfer(tenant_id,transfer_no,transfer_date,from_location_id,to_location_id,created_by) values($1,'LT-EVIDENCE','2026-04-02',$2,$3,$4) returning id`,[tenantId,main.rows[0]!.id,branch.body.id,ownerId]);transferId=transfer.rows[0]!.id;}finally{await client2.end();}});

test('PDF evidence is hashed, listed, downloaded and cannot be duplicated',async()=>{const pdf=Buffer.from('%PDF-1.4\nMilestone evidence\n%%EOF');const added=await api('/attachments',{method:'POST',token,body:{docType:'location_transfer',docId:transferId,fileName:'signed transfer.pdf',contentType:'application/pdf',dataBase64:pdf.toString('base64'),note:'Signed by both godowns'}});assert.equal(added.status,201,JSON.stringify(added.body));assert.equal(added.body.byteSize,pdf.length);assert.match(added.body.sha256,/^[0-9a-f]{64}$/);const duplicate=await api('/attachments',{method:'POST',token,body:{docType:'location_transfer',docId:transferId,fileName:'copy.pdf',contentType:'application/pdf',dataBase64:pdf.toString('base64')}});assert.equal(duplicate.status,409);const list=await api(`/attachments?docType=location_transfer&docId=${transferId}`,{token});assert.equal(list.status,200);assert.equal(list.body.length,1);assert.equal(list.body[0].note,'Signed by both godowns');const download=await fetch(`${BASE}/api/attachments/${added.body.id}/download`,{headers:{authorization:`Bearer ${token}`}});assert.equal(download.status,200);assert.deepEqual(Buffer.from(await download.arrayBuffer()),pdf);const removed=await api(`/attachments/${added.body.id}/remove`,{method:'POST',token,body:{reason:'Superseded by corrected signed copy'}});assert.equal(removed.status,200);const gone=await fetch(`${BASE}/api/attachments/${added.body.id}/download`,{headers:{authorization:`Bearer ${token}`}});assert.equal(gone.status,404);const client=db();await client.connect();try{const evidence=await client.query(`select byte_size,status from document_attachment where id=$1`,[added.body.id]);assert.deepEqual(evidence.rows[0],{byte_size:pdf.length,status:'removed'});const events=await client.query(`select event from document_attachment_event where attachment_id=$1 order by id`,[added.body.id]);assert.deepEqual(events.rows.map(row=>row.event),['added','removed']);}finally{await client.end();}});

test('declared file type must match actual bytes',async()=>{const bad=await api('/attachments',{method:'POST',token,body:{docType:'location_transfer',docId:transferId,fileName:'not-really.pdf',contentType:'application/pdf',dataBase64:Buffer.from('plain text').toString('base64')}});assert.equal(bad.status,400);assert.match(bad.body.error,/does not match/i);});

test('opening bills import as one transaction and a bad row rolls all rows back',async()=>{const client=db();await client.connect();try{const control=await client.query<{id:string}>(`select id from control_account where tenant_id=$1 and nature='sundry_debtor_finish'`,[tenantId]);const debtor=await client.query<{id:string}>(`insert into ledger_account(tenant_id,code,name,control_account_id,gst_reg_type) values($1,'OPEN-CUST','Opening Customer',$2,'unregistered') returning id`,[tenantId,control.rows[0]!.id]);debtorId=debtor.rows[0]!.id;}finally{await client.end();}const imported=await api('/opening-outstandings/batch',{method:'POST',token,body:{entries:[{fyLabel:'2026-27',kind:'receivable',partyId:debtorId,referenceNo:'OLD-1',documentDate:'2026-03-01',dueDate:'2026-04-01',originalAmount:1000},{fyLabel:'2026-27',kind:'receivable',partyId:debtorId,referenceNo:'OLD-2',documentDate:'2026-03-02',dueDate:'2026-04-02',originalAmount:2000}]}});assert.equal(imported.status,201,JSON.stringify(imported.body));assert.equal(imported.body.imported,2);const failed=await api('/opening-outstandings/batch',{method:'POST',token,body:{entries:[{fyLabel:'2026-27',kind:'receivable',partyId:debtorId,referenceNo:'ROLLBACK-1',documentDate:'2026-03-03',dueDate:'2026-04-03',originalAmount:1},{fyLabel:'2026-27',kind:'receivable',partyId:'00000000-0000-0000-0000-000000000000',referenceNo:'ROLLBACK-2',documentDate:'2026-03-03',dueDate:'2026-04-03',originalAmount:1}]}});assert.equal(failed.status,400);const list=await api('/opening-outstandings',{token});assert.equal(list.body.some((row:{reference_no:string})=>row.reference_no.startsWith('ROLLBACK-')),false);});
