/** Shared customization, report-builder and integration-feed contracts. */
import test from 'node:test';
import assert from 'node:assert/strict';

const BASE=process.env.API_BASE??'http://127.0.0.1:4000';
const LEDGER='33333333-0000-0000-0000-000000000701';
const stamp=Date.now();let owner='';let viewer='';let fieldId='';let reportId='';let connectionId='';let key='';let deliveryId=0;
async function api(path:string,opts:{method?:string;body?:unknown;token?:string;integrationKey?:string}={}){const response=await fetch(`${BASE}/api${path}`,{method:opts.method??'GET',headers:{'content-type':'application/json',...(opts.token?{authorization:`Bearer ${opts.token}`}:{}) ,...(opts.integrationKey?{'x-erp-integration-key':opts.integrationKey}:{})},body:opts.body===undefined?undefined:JSON.stringify(opts.body)});const text=await response.text();return{status:response.status,body:text?JSON.parse(text):null};}
async function login(email:string){return api('/auth/login',{method:'POST',body:{email,password:'changeme'}});}

test('platform users sign in and discover only allow-listed entities and report sources',async()=>{owner=(await login('owner@neelkamal.test')).body.token;viewer=(await login('viewer@neelkamal.test')).body.token;const entities=await api('/platform/entities',{token:viewer});assert.equal(entities.status,200);assert.ok(entities.body.includes('sales_invoice'));assert.ok(entities.body.includes('edition_document'));assert.ok(entities.body.includes('edition_resource'));const sources=await api('/platform/report-sources',{token:viewer});assert.equal(sources.status,200);assert.ok(sources.body.some((row:any)=>row.key==='trial_balance'));assert.ok(sources.body.some((row:any)=>row.key==='edition_operations'));assert.ok(sources.body.some((row:any)=>row.key==='edition_stock'));assert.ok(sources.body.some((row:any)=>row.key==='edition_job_cost'));});

test('typed custom fields attach to real records and reject the wrong JSON type',async()=>{const made=await api('/platform/custom-fields',{method:'POST',token:owner,body:{entityType:'ledger_account',fieldKey:`buyer_segment_${String(stamp).slice(-5)}`,label:'Buyer segment',dataType:'choice',choices:['Retail','Wholesale'],required:false}});assert.equal(made.status,201,JSON.stringify(made.body));fieldId=made.body.id;
  const forbidden=await api('/platform/custom-fields',{method:'POST',token:viewer,body:{entityType:'ledger_account',fieldKey:'forbidden_field',label:'Forbidden',dataType:'text'}});assert.equal(forbidden.status,403);
  const wrong=await api('/platform/custom-values',{method:'POST',token:owner,body:{entityType:'ledger_account',entityId:LEDGER,values:[{definitionId:fieldId,value:42}]}});assert.equal(wrong.status,400,JSON.stringify(wrong.body));assert.match(wrong.body.error,/allowed choice/i);
  const saved=await api('/platform/custom-values',{method:'POST',token:owner,body:{entityType:'ledger_account',entityId:LEDGER,values:[{definitionId:fieldId,value:'Wholesale'}]}});assert.equal(saved.status,200,JSON.stringify(saved.body));const values=await api(`/platform/custom-values?entityType=ledger_account&entityId=${LEDGER}`,{token:viewer});assert.equal(values.status,200);assert.equal(values.body.find((row:any)=>row.id===fieldId).value,'Wholesale');});

test('report builder stores only allow-listed columns and runs bound filters',async()=>{const bad=await api('/platform/reports',{method:'POST',token:owner,body:{name:`Unsafe ${stamp}`,sourceKey:'trial_balance',columns:['code','drop table tenant'],filters:[],isShared:true}});assert.equal(bad.status,400);
  const made=await api('/platform/reports',{method:'POST',token:owner,body:{name:`Cash ledgers ${stamp}`,description:'Reusable filtered accounting view',sourceKey:'trial_balance',columns:['code','name','balance'],filters:[{column:'name',operator:'contains',value:'cash'}],sort:{column:'code',direction:'asc'},isShared:true}});assert.equal(made.status,201,JSON.stringify(made.body));reportId=made.body.id;const run=await api(`/platform/reports/${reportId}/run`,{method:'POST',token:viewer,body:{limit:50}});assert.equal(run.status,200,JSON.stringify(run.body));assert.ok(run.body.rows.every((row:any)=>Object.keys(row).every(key=>['code','name','balance'].includes(key))));});

test('integration connection returns its key once and exposes an idempotent pull feed',async()=>{const made=await api('/platform/integrations',{method:'POST',token:owner,body:{name:`Warehouse bridge ${stamp}`,adapter:'pull_api',description:'Test adapter',subscriptions:['sales_invoice.created']}});assert.equal(made.status,201,JSON.stringify(made.body));connectionId=made.body.id;key=made.body.token;assert.match(key,/^lerp_/);
  const event=await api(`/platform/integrations/${connectionId}/events`,{method:'POST',token:owner,body:{eventType:'stock.snapshot.ready',entityId:LEDGER,payload:{source:'platform-test',rows:3}}});assert.equal(event.status,201,JSON.stringify(event.body));deliveryId=event.body.deliveryId;
  const denied=await api('/integrations/feed',{integrationKey:'lerp_wrong'});assert.equal(denied.status,401);const feed=await api('/integrations/feed',{integrationKey:key});assert.equal(feed.status,200,JSON.stringify(feed.body));assert.equal(feed.body.rows.filter((row:any)=>row.id===deliveryId).length,1);
  const ack=await api(`/integrations/feed/${deliveryId}/ack`,{method:'POST',integrationKey:key,body:{status:'delivered'}});assert.equal(ack.status,200,JSON.stringify(ack.body));const duplicate=await api(`/integrations/feed/${deliveryId}/ack`,{method:'POST',integrationKey:key,body:{status:'delivered'}});assert.equal(duplicate.status,404);const empty=await api('/integrations/feed',{integrationKey:key});assert.equal(empty.body.rows.some((row:any)=>row.id===deliveryId),false);});

test('rotating a feed key kills the old credential immediately',async()=>{const rotated=await api(`/platform/integrations/${connectionId}/token`,{method:'POST',token:owner,body:{}});assert.equal(rotated.status,200,JSON.stringify(rotated.body));const old=await api('/integrations/feed',{integrationKey:key});assert.equal(old.status,401);const fresh=await api('/integrations/feed',{integrationKey:rotated.body.token});assert.equal(fresh.status,200);});
