import {Router,type Request} from 'express';
import {z} from 'zod';
import {many,one,withTenant,type Db} from './db.ts';
import {requireWrite,type Permission} from './auth.ts';
import {sendCsv} from './listing.ts';

const edition=z.enum(['weaving','dyeing','exports','logistics','garments']);const uuid=z.string().uuid();const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);const text=(n=120)=>z.string().trim().min(1).max(n);const pos=z.coerce.number().finite().positive();const nonneg=z.coerce.number().finite().nonnegative();
type Field={key:string;label:string;type:'text'|'number'|'date'|'select'|'textarea';required?:boolean;options?:string[];unit?:string};
type Workflow={label:string;prefix:string;schema:z.ZodTypeAny;fields:Field[]};
const f=(key:string,label:string,type:Field['type']='text',extra:Partial<Field>={}):Field=>({key,label,type,required:true,...extra});
export const EDITION_WORKFLOWS:Record<z.infer<typeof edition>,Record<string,Workflow>>={
  weaving:{
    loom_plan:{label:'Loom plan',prefix:'WV/LP/',schema:z.object({loomNo:text(30),quality:text(),warpCount:pos,weftCount:pos,reed:pos,pick:pos,plannedMetres:pos,beamNo:text(40),startDate:date,targetDate:date}).strict(),fields:[f('loomNo','Loom number'),f('quality','Quality'),f('warpCount','Warp count','number'),f('weftCount','Weft count','number'),f('reed','Reed','number'),f('pick','Pick','number'),f('plannedMetres','Planned metres','number',{unit:'MTR'}),f('beamNo','Beam number'),f('startDate','Start date','date'),f('targetDate','Target date','date')]},
    beam_issue:{label:'Beam and yarn issue',prefix:'WV/BI/',schema:z.object({loomNo:text(30),beamNo:text(40),yarnLots:text(500),issuedKg:pos,expectedMetres:pos,weaver:text(100)}).strict(),fields:[f('loomNo','Loom number'),f('beamNo','Beam number'),f('yarnLots','Yarn lots','textarea'),f('issuedKg','Issued weight','number',{unit:'KGS'}),f('expectedMetres','Expected metres','number',{unit:'MTR'}),f('weaver','Weaver / operator')]},
    production_entry:{label:'Loom production entry',prefix:'WV/PR/',schema:z.object({loomNo:text(30),shift:z.enum(['A','B','C','general']),operator:text(100),producedMetres:pos,rejectionMetres:nonneg,stops:z.coerce.number().int().nonnegative(),productionDate:date}).strict(),fields:[f('loomNo','Loom number'),f('shift','Shift','select',{options:['A','B','C','general']}),f('operator','Operator'),f('producedMetres','Produced metres','number',{unit:'MTR'}),f('rejectionMetres','Rejected metres','number',{unit:'MTR'}),f('stops','Loom stops','number'),f('productionDate','Production date','date')]},
    yarn_receipt:{label:'Yarn purchase / receipt',prefix:'WV/YR/',schema:z.object({supplier:text(),invoiceRef:text(80),yarnCount:text(40),lotNo:text(50),cones:z.coerce.number().int().positive(),netKg:pos,ratePerKg:pos,receivedDate:date}).strict(),fields:[f('supplier','Yarn supplier'),f('invoiceRef','Supplier invoice'),f('yarnCount','Yarn count'),f('lotNo','Lot number'),f('cones','Cones','number'),f('netKg','Net weight','number',{unit:'KGS'}),f('ratePerKg','Rate','number',{unit:'₹/KGS'}),f('receivedDate','Received date','date')]},
    warping_order:{label:'Warping order',prefix:'WV/WO/',schema:z.object({quality:text(),yarnLot:text(80),ends:z.coerce.number().int().positive(),lengthMetres:pos,beamCount:z.coerce.number().int().positive(),machine:text(50),targetDate:date}).strict(),fields:[f('quality','Quality'),f('yarnLot','Yarn lot'),f('ends','Ends','number'),f('lengthMetres','Warp length','number',{unit:'MTR'}),f('beamCount','Beam count','number'),f('machine','Warping machine'),f('targetDate','Target date','date')]},
    sizing_batch:{label:'Sizing batch',prefix:'WV/SZ/',schema:z.object({warpingRef:text(80),sizeRecipe:text(120),inputKg:pos,beamCount:z.coerce.number().int().positive(),sizePickupPct:nonneg.max(100),machine:text(50),completedDate:date}).strict(),fields:[f('warpingRef','Warping reference'),f('sizeRecipe','Size recipe'),f('inputKg','Input weight','number',{unit:'KGS'}),f('beamCount','Beams','number'),f('sizePickupPct','Size pickup','number',{unit:'%'}),f('machine','Sizing machine'),f('completedDate','Completion date','date')]},
    fabric_inspection:{label:'Grey fabric inspection',prefix:'WV/FI/',schema:z.object({productionRef:text(80),rollNo:text(50),metres:pos,grade:z.enum(['A','B','C','reject']),defectPoints:nonneg,widthCm:pos,inspector:text(100)}).strict(),fields:[f('productionRef','Production reference'),f('rollNo','Roll number'),f('metres','Inspected metres','number',{unit:'MTR'}),f('grade','Grade','select',{options:['A','B','C','reject']}),f('defectPoints','Defect points','number'),f('widthCm','Width','number',{unit:'CM'}),f('inspector','Inspector')]},
    jobwork_settlement:{label:'Weaver job-work settlement',prefix:'WV/JS/',schema:z.object({weaver:text(),periodFrom:date,periodTo:date,acceptedMetres:pos,rejectedMetres:nonneg,ratePerMetre:pos,deductions:nonneg,settlementRef:text(80)}).strict(),fields:[f('weaver','Weaver'),f('periodFrom','Period from','date'),f('periodTo','Period to','date'),f('acceptedMetres','Accepted metres','number',{unit:'MTR'}),f('rejectedMetres','Rejected metres','number',{unit:'MTR'}),f('ratePerMetre','Job rate','number',{unit:'₹/MTR'}),f('deductions','Deductions','number',{unit:'₹'}),f('settlementRef','Settlement reference')]},
    loom_maintenance:{label:'Loom maintenance',prefix:'WV/MT/',schema:z.object({loomNo:text(30),maintenanceType:z.enum(['preventive','breakdown','changeover']),stoppedAt:date,hours:pos,technician:text(100),partsUsed:text(500),resolution:text(500)}).strict(),fields:[f('loomNo','Loom number'),f('maintenanceType','Maintenance type','select',{options:['preventive','breakdown','changeover']}),f('stoppedAt','Maintenance date','date'),f('hours','Downtime','number',{unit:'HRS'}),f('technician','Technician'),f('partsUsed','Parts used','textarea'),f('resolution','Resolution','textarea')]}
  },
  dyeing:{
    batch_card:{label:'Dyeing batch card',prefix:'DY/BC/',schema:z.object({batchRef:text(50),quality:text(),shade:text(),colour:text(),machine:text(50),inputKg:pos,inputMetres:pos,recipeRef:text(80),targetDate:date}).strict(),fields:[f('batchRef','Batch reference'),f('quality','Quality'),f('shade','Shade'),f('colour','Colour'),f('machine','Machine'),f('inputKg','Input weight','number',{unit:'KGS'}),f('inputMetres','Input metres','number',{unit:'MTR'}),f('recipeRef','Recipe reference'),f('targetDate','Target date','date')]},
    process_stage:{label:'Process stage entry',prefix:'DY/PS/',schema:z.object({batchRef:text(50),stage:z.enum(['scouring','bleaching','dyeing','washing','finishing','stenter','compacting']),temperature:nonneg,durationMinutes:pos,chemicals:text(1000),operator:text(100)}).strict(),fields:[f('batchRef','Batch reference'),f('stage','Process stage','select',{options:['scouring','bleaching','dyeing','washing','finishing','stenter','compacting']}),f('temperature','Temperature','number',{unit:'°C'}),f('durationMinutes','Duration','number',{unit:'MIN'}),f('chemicals','Chemicals and dosage','textarea'),f('operator','Operator')]},
    quality_release:{label:'Dyeing quality release',prefix:'DY/QR/',schema:z.object({batchRef:text(50),result:z.enum(['pass','rework','reject']),gsm:pos,widthCm:pos,shrinkagePct:nonneg.max(100),shadeDelta:text(80),remarks:z.string().max(500)}).strict(),fields:[f('batchRef','Batch reference'),f('result','Release result','select',{options:['pass','rework','reject']}),f('gsm','GSM','number'),f('widthCm','Width','number',{unit:'CM'}),f('shrinkagePct','Shrinkage','number',{unit:'%'}),f('shadeDelta','Shade result'),f('remarks','QC remarks','textarea',{required:false})]},
    lab_dip:{label:'Lab dip approval',prefix:'DY/LD/',schema:z.object({buyer:text(),quality:text(),shade:text(),standardRef:text(80),trialNo:z.coerce.number().int().positive(),result:z.enum(['submitted','approved','rejected','resubmit']),deltaE:nonneg,approvedBy:text(100)}).strict(),fields:[f('buyer','Buyer'),f('quality','Quality'),f('shade','Shade'),f('standardRef','Colour standard'),f('trialNo','Trial number','number'),f('result','Result','select',{options:['submitted','approved','rejected','resubmit']}),f('deltaE','Delta E','number'),f('approvedBy','Approved / reviewed by')]},
    recipe_card:{label:'Dye recipe',prefix:'DY/RC/',schema:z.object({recipeCode:text(40),quality:text(),shade:text(),liquorRatio:text(30),dyes:text(1000),chemicals:text(1000),temperature:nonneg,durationMinutes:pos}).strict(),fields:[f('recipeCode','Recipe code'),f('quality','Quality'),f('shade','Shade'),f('liquorRatio','Liquor ratio'),f('dyes','Dyes and dosage','textarea'),f('chemicals','Chemicals and dosage','textarea'),f('temperature','Temperature','number',{unit:'°C'}),f('durationMinutes','Duration','number',{unit:'MIN'})]},
    chemical_receipt:{label:'Dye / chemical receipt',prefix:'DY/CR/',schema:z.object({supplier:text(),invoiceRef:text(80),materialCode:text(50),lotNo:text(50),quantityKg:pos,ratePerKg:pos,expiryDate:date,receivedDate:date}).strict(),fields:[f('supplier','Supplier'),f('invoiceRef','Supplier invoice'),f('materialCode','Dye / chemical'),f('lotNo','Lot number'),f('quantityKg','Quantity','number',{unit:'KGS'}),f('ratePerKg','Rate','number',{unit:'₹/KGS'}),f('expiryDate','Expiry date','date'),f('receivedDate','Received date','date')]},
    machine_schedule:{label:'Dyeing machine schedule',prefix:'DY/MS/',schema:z.object({machine:text(50),batchRef:text(50),plannedStart:date,plannedEnd:date,capacityKg:pos,plannedKg:pos,priority:z.enum(['low','normal','high','urgent'])}).strict().refine(v=>v.plannedKg<=v.capacityKg,'planned load cannot exceed machine capacity'),fields:[f('machine','Machine'),f('batchRef','Batch reference'),f('plannedStart','Planned start','date'),f('plannedEnd','Planned end','date'),f('capacityKg','Capacity','number',{unit:'KGS'}),f('plannedKg','Planned load','number',{unit:'KGS'}),f('priority','Priority','select',{options:['low','normal','high','urgent']})]},
    reprocess_order:{label:'Dyeing reprocess',prefix:'DY/RP/',schema:z.object({batchRef:text(50),failureReason:text(500),correctiveRecipe:text(80),reprocessStage:z.enum(['dyeing','washing','finishing','stenter','compacting']),quantityKg:pos,authorisedBy:text(100),targetDate:date}).strict(),fields:[f('batchRef','Original batch'),f('failureReason','Failure reason','textarea'),f('correctiveRecipe','Corrective recipe'),f('reprocessStage','Reprocess stage','select',{options:['dyeing','washing','finishing','stenter','compacting']}),f('quantityKg','Quantity','number',{unit:'KGS'}),f('authorisedBy','Authorised by'),f('targetDate','Target date','date')]},
    batch_costing:{label:'Dyeing batch costing',prefix:'DY/CO/',schema:z.object({batchRef:text(50),outputKg:pos,chemicalCost:nonneg,powerCost:nonneg,labourCost:nonneg,machineCost:nonneg,overheadCost:nonneg}).strict(),fields:[f('batchRef','Batch reference'),f('outputKg','Output weight','number',{unit:'KGS'}),f('chemicalCost','Chemical cost','number',{unit:'₹'}),f('powerCost','Power cost','number',{unit:'₹'}),f('labourCost','Labour cost','number',{unit:'₹'}),f('machineCost','Machine cost','number',{unit:'₹'}),f('overheadCost','Overhead cost','number',{unit:'₹'})]}
  },
  exports:{
    export_order:{label:'Export order',prefix:'EX/EO/',schema:z.object({buyer:text(),country:text(80),incoterm:z.enum(['EXW','FOB','CIF','CFR','DAP','DDP']),currency:z.enum(['USD','EUR','GBP','AED','INR']),orderValue:pos,shipmentDate:date,portOfLoading:text(),portOfDischarge:text()}).strict(),fields:[f('buyer','Overseas buyer'),f('country','Destination country'),f('incoterm','Incoterm','select',{options:['EXW','FOB','CIF','CFR','DAP','DDP']}),f('currency','Currency','select',{options:['USD','EUR','GBP','AED','INR']}),f('orderValue','Order value','number'),f('shipmentDate','Shipment date','date'),f('portOfLoading','Port of loading'),f('portOfDischarge','Port of discharge')]},
    shipment:{label:'Export shipment',prefix:'EX/SH/',schema:z.object({exportOrderRef:text(80),invoiceNo:text(80),containerNo:text(30),sealNo:text(30),packages:z.coerce.number().int().positive(),grossWeightKg:pos,netWeightKg:pos,vessel:text(100),etd:date,eta:date}).strict().refine(v=>v.netWeightKg<=v.grossWeightKg,'net weight cannot exceed gross weight'),fields:[f('exportOrderRef','Export order reference'),f('invoiceNo','Commercial invoice'),f('containerNo','Container number'),f('sealNo','Seal number'),f('packages','Packages','number'),f('grossWeightKg','Gross weight','number',{unit:'KGS'}),f('netWeightKg','Net weight','number',{unit:'KGS'}),f('vessel','Vessel / flight'),f('etd','ETD','date'),f('eta','ETA','date')]},
    compliance_pack:{label:'Export compliance pack',prefix:'EX/CP/',schema:z.object({shipmentRef:text(80),shippingBillNo:text(80),shippingBillDate:date,lutBondNo:text(80),certificateOriginNo:text(80),bankRealisationStatus:z.enum(['not_due','pending','received'])}).strict(),fields:[f('shipmentRef','Shipment reference'),f('shippingBillNo','Shipping bill number'),f('shippingBillDate','Shipping bill date','date'),f('lutBondNo','LUT / bond number'),f('certificateOriginNo','Certificate of origin'),f('bankRealisationStatus','Realisation status','select',{options:['not_due','pending','received']})]},
    letter_of_credit:{label:'Letter of credit',prefix:'EX/LC/',schema:z.object({buyer:text(),bank:text(),lcNo:text(80),currency:z.enum(['USD','EUR','GBP','AED','INR']),lcValue:pos,issueDate:date,expiryDate:date,lastShipmentDate:date,terms:text(1000)}).strict(),fields:[f('buyer','Buyer'),f('bank','Issuing bank'),f('lcNo','LC number'),f('currency','Currency','select',{options:['USD','EUR','GBP','AED','INR']}),f('lcValue','LC value','number'),f('issueDate','Issue date','date'),f('expiryDate','Expiry date','date'),f('lastShipmentDate','Last shipment date','date'),f('terms','Documentary terms','textarea')]},
    pre_shipment_check:{label:'Pre-shipment inspection',prefix:'EX/PS/',schema:z.object({orderRef:text(80),inspectionAgency:text(),inspectionDate:date,packages:z.coerce.number().int().positive(),quantity:pos,result:z.enum(['pass','conditional','fail']),certificateRef:text(80),exceptions:z.string().max(500)}).strict(),fields:[f('orderRef','Export order'),f('inspectionAgency','Inspection agency'),f('inspectionDate','Inspection date','date'),f('packages','Packages','number'),f('quantity','Quantity','number'),f('result','Result','select',{options:['pass','conditional','fail']}),f('certificateRef','Certificate reference'),f('exceptions','Exceptions','textarea',{required:false})]},
    commercial_document_pack:{label:'Commercial document pack',prefix:'EX/DP/',schema:z.object({shipmentRef:text(80),commercialInvoice:text(80),packingList:text(80),billOfLading:text(80),insuranceCertificate:text(80),certificateOfOrigin:text(80),documentsPresentedDate:date}).strict(),fields:[f('shipmentRef','Shipment reference'),f('commercialInvoice','Commercial invoice'),f('packingList','Packing list'),f('billOfLading','Bill of lading / AWB'),f('insuranceCertificate','Insurance certificate'),f('certificateOfOrigin','Certificate of origin'),f('documentsPresentedDate','Presented to bank','date')]},
    duty_benefit_claim:{label:'Drawback / RoDTEP claim',prefix:'EX/DB/',schema:z.object({shippingBillNo:text(80),scheme:z.enum(['drawback','rodtep','rosctl','advance_authorisation']),eligibleFob:pos,claimAmount:nonneg,claimRef:text(80),status:z.enum(['prepared','submitted','queried','sanctioned','rejected']),statusDate:date}).strict(),fields:[f('shippingBillNo','Shipping bill'),f('scheme','Scheme','select',{options:['drawback','rodtep','rosctl','advance_authorisation']}),f('eligibleFob','Eligible FOB','number'),f('claimAmount','Claim amount','number'),f('claimRef','Claim reference'),f('status','Claim status','select',{options:['prepared','submitted','queried','sanctioned','rejected']}),f('statusDate','Status date','date')]},
    forex_realisation:{label:'Export payment realisation',prefix:'EX/FR/',schema:z.object({invoiceNo:text(80),bank:text(),currency:z.enum(['USD','EUR','GBP','AED','INR']),invoiceValue:pos,receivedValue:pos,exchangeRate:pos,receivedDate:date,bankReference:text(100),edpmsStatus:z.enum(['open','part_realised','realised','written_off'])}).strict().refine(v=>v.receivedValue<=v.invoiceValue,'received value cannot exceed invoice value'),fields:[f('invoiceNo','Export invoice'),f('bank','Receiving bank'),f('currency','Currency','select',{options:['USD','EUR','GBP','AED','INR']}),f('invoiceValue','Invoice value','number'),f('receivedValue','Received value','number'),f('exchangeRate','Exchange rate','number'),f('receivedDate','Received date','date'),f('bankReference','Bank reference / FIRC'),f('edpmsStatus','EDPMS status','select',{options:['open','part_realised','realised','written_off']})]},
    bank_closure:{label:'Export bank closure',prefix:'EX/CL/',schema:z.object({invoiceNo:text(80),shippingBillNo:text(80),bankReference:text(100),brcNo:text(80),realisedAmount:pos,closureDate:date,exceptions:z.string().max(500)}).strict(),fields:[f('invoiceNo','Export invoice'),f('shippingBillNo','Shipping bill'),f('bankReference','Bank reference'),f('brcNo','e-BRC number'),f('realisedAmount','Realised amount','number'),f('closureDate','Closure date','date'),f('exceptions','Exceptions / write-off','textarea',{required:false})]}
  },
  logistics:{
    consignment:{label:'Consignment / LR',prefix:'LG/LR/',schema:z.object({lrNo:text(50),consignor:text(),consignee:text(),origin:text(),destination:text(),packages:z.coerce.number().int().positive(),weightKg:pos,vehicleNo:text(20),driver:text(100),driverMobile:z.string().regex(/^\+?[1-9]\d{9,14}$/)}).strict(),fields:[f('lrNo','LR number'),f('consignor','Consignor'),f('consignee','Consignee'),f('origin','Origin'),f('destination','Destination'),f('packages','Packages','number'),f('weightKg','Weight','number',{unit:'KGS'}),f('vehicleNo','Vehicle number'),f('driver','Driver'),f('driverMobile','Driver mobile')]},
    trip:{label:'Vehicle trip',prefix:'LG/TR/',schema:z.object({tripRef:text(50),vehicleNo:text(20),driver:text(100),origin:text(),destination:text(),departedAt:date,expectedAt:date,distanceKm:pos}).strict(),fields:[f('tripRef','Trip reference'),f('vehicleNo','Vehicle number'),f('driver','Driver'),f('origin','Origin'),f('destination','Destination'),f('departedAt','Departure date','date'),f('expectedAt','Expected delivery','date'),f('distanceKm','Distance','number',{unit:'KM'})]},
    delivery_proof:{label:'Proof of delivery',prefix:'LG/POD/',schema:z.object({consignmentRef:text(80),deliveredAt:date,receiverName:text(100),condition:z.enum(['good','short','damaged','refused']),podReference:text(100),exception:z.string().max(500)}).strict(),fields:[f('consignmentRef','Consignment reference'),f('deliveredAt','Delivered date','date'),f('receiverName','Received by'),f('condition','Condition','select',{options:['good','short','damaged','refused']}),f('podReference','POD reference'),f('exception','Exception / damage note','textarea',{required:false})]},
    route_plan:{label:'Route and load plan',prefix:'LG/RP/',schema:z.object({routeCode:text(40),origin:text(),destination:text(),via:text(500),distanceKm:pos,vehicleType:text(80),capacityKg:pos,plannedWeightKg:pos,plannedDate:date}).strict().refine(v=>v.plannedWeightKg<=v.capacityKg,'planned weight cannot exceed capacity'),fields:[f('routeCode','Route code'),f('origin','Origin'),f('destination','Destination'),f('via','Via / stops','textarea'),f('distanceKm','Distance','number',{unit:'KM'}),f('vehicleType','Vehicle type'),f('capacityKg','Vehicle capacity','number',{unit:'KGS'}),f('plannedWeightKg','Planned weight','number',{unit:'KGS'}),f('plannedDate','Planned date','date')]},
    fuel_toll_expense:{label:'Trip fuel and toll',prefix:'LG/FE/',schema:z.object({tripRef:text(50),vehicleNo:text(20),fuelLitres:nonneg,fuelAmount:nonneg,tollAmount:nonneg,driverAdvance:nonneg,otherAmount:nonneg,expenseDate:date,receipts:text(500)}).strict(),fields:[f('tripRef','Trip reference'),f('vehicleNo','Vehicle number'),f('fuelLitres','Fuel','number',{unit:'LTR'}),f('fuelAmount','Fuel amount','number',{unit:'₹'}),f('tollAmount','Toll amount','number',{unit:'₹'}),f('driverAdvance','Driver advance','number',{unit:'₹'}),f('otherAmount','Other expense','number',{unit:'₹'}),f('expenseDate','Expense date','date'),f('receipts','Receipt references','textarea')]},
    vehicle_maintenance:{label:'Vehicle maintenance',prefix:'LG/VM/',schema:z.object({vehicleNo:text(20),maintenanceType:z.enum(['service','repair','tyre','insurance','permit','fitness']),vendor:text(),odometerKm:nonneg,amount:nonneg,serviceDate:date,nextDueDate:date,details:text(500)}).strict(),fields:[f('vehicleNo','Vehicle number'),f('maintenanceType','Maintenance type','select',{options:['service','repair','tyre','insurance','permit','fitness']}),f('vendor','Vendor'),f('odometerKm','Odometer','number',{unit:'KM'}),f('amount','Amount','number',{unit:'₹'}),f('serviceDate','Service date','date'),f('nextDueDate','Next due','date'),f('details','Work details','textarea')]},
    freight_invoice:{label:'Freight invoice',prefix:'LG/FI/',schema:z.object({consignmentRef:text(80),customer:text(),billingBasis:z.enum(['trip','weight','package','distance']),basisQty:pos,rate:pos,detention:nonneg,loading:nonneg,otherCharges:nonneg,taxAmount:nonneg}).strict(),fields:[f('consignmentRef','Consignment / LR'),f('customer','Customer'),f('billingBasis','Billing basis','select',{options:['trip','weight','package','distance']}),f('basisQty','Billing quantity','number'),f('rate','Rate','number'),f('detention','Detention','number',{unit:'₹'}),f('loading','Loading / unloading','number',{unit:'₹'}),f('otherCharges','Other charges','number',{unit:'₹'}),f('taxAmount','Tax amount','number',{unit:'₹'})]},
    transporter_settlement:{label:'Transporter settlement',prefix:'LG/TS/',schema:z.object({transporter:text(),periodFrom:date,periodTo:date,trips:z.coerce.number().int().positive(),grossFreight:pos,advances:nonneg,deductions:nonneg,tds:nonneg,settlementRef:text(80)}).strict(),fields:[f('transporter','Transporter'),f('periodFrom','Period from','date'),f('periodTo','Period to','date'),f('trips','Trips','number'),f('grossFreight','Gross freight','number',{unit:'₹'}),f('advances','Advances','number',{unit:'₹'}),f('deductions','Deductions','number',{unit:'₹'}),f('tds','TDS','number',{unit:'₹'}),f('settlementRef','Settlement reference')]}
  },
  garments:{
    style:{label:'Garment style',prefix:'GM/ST/',schema:z.object({styleCode:text(40),buyer:text(),season:text(50),garment:text(80),fabric:text(),colour:text(80),sizeRange:text(80),orderQty:z.coerce.number().int().positive()}).strict(),fields:[f('styleCode','Style code'),f('buyer','Buyer'),f('season','Season'),f('garment','Garment'),f('fabric','Fabric'),f('colour','Colour'),f('sizeRange','Size range'),f('orderQty','Order quantity','number',{unit:'PCS'})]},
    cutting_order:{label:'Cutting order',prefix:'GM/CT/',schema:z.object({styleRef:text(80),markerNo:text(50),fabricLot:text(80),plannedQty:z.coerce.number().int().positive(),layCount:z.coerce.number().int().positive(),cutQty:z.coerce.number().int().nonnegative(),wastagePct:nonneg.max(100)}).strict(),fields:[f('styleRef','Style reference'),f('markerNo','Marker number'),f('fabricLot','Fabric lot'),f('plannedQty','Planned quantity','number',{unit:'PCS'}),f('layCount','Lay count','number'),f('cutQty','Cut quantity','number',{unit:'PCS'}),f('wastagePct','Wastage','number',{unit:'%'})]},
    production_batch:{label:'Garment production batch',prefix:'GM/PB/',schema:z.object({styleRef:text(80),lineNo:text(30),operation:z.enum(['cutting','stitching','washing','finishing','packing']),plannedQty:z.coerce.number().int().positive(),completedQty:z.coerce.number().int().nonnegative(),rejectedQty:z.coerce.number().int().nonnegative(),shift:z.enum(['A','B','C','general']),productionDate:date}).strict(),fields:[f('styleRef','Style reference'),f('lineNo','Production line'),f('operation','Operation','select',{options:['cutting','stitching','washing','finishing','packing']}),f('plannedQty','Planned quantity','number',{unit:'PCS'}),f('completedQty','Completed quantity','number',{unit:'PCS'}),f('rejectedQty','Rejected quantity','number',{unit:'PCS'}),f('shift','Shift','select',{options:['A','B','C','general']}),f('productionDate','Production date','date')]},
    sample:{label:'Garment sample approval',prefix:'GM/SA/',schema:z.object({styleCode:text(40),sampleType:z.enum(['development','fit','size_set','pp','sealer','shipment']),version:z.coerce.number().int().positive(),submittedDate:date,result:z.enum(['submitted','approved','rejected','resubmit']),buyerComments:text(1000),approvedDate:date}).strict(),fields:[f('styleCode','Style code'),f('sampleType','Sample type','select',{options:['development','fit','size_set','pp','sealer','shipment']}),f('version','Version','number'),f('submittedDate','Submitted date','date'),f('result','Result','select',{options:['submitted','approved','rejected','resubmit']}),f('buyerComments','Buyer comments','textarea'),f('approvedDate','Decision date','date')]},
    bom:{label:'Style bill of materials',prefix:'GM/BM/',schema:z.object({styleRef:text(80),version:z.coerce.number().int().positive(),fabricConsumption:pos,fabricUom:z.enum(['MTR','KGS','YDS']),trimSummary:text(1000),threadMetres:nonneg,packagingSummary:text(500),effectiveDate:date}).strict(),fields:[f('styleRef','Style reference'),f('version','BOM version','number'),f('fabricConsumption','Fabric per garment','number'),f('fabricUom','Fabric UOM','select',{options:['MTR','KGS','YDS']}),f('trimSummary','Trims and quantities','textarea'),f('threadMetres','Thread per garment','number',{unit:'MTR'}),f('packagingSummary','Packaging','textarea'),f('effectiveDate','Effective date','date')]},
    size_colour_order:{label:'Size-colour order matrix',prefix:'GM/MX/',schema:z.object({styleRef:text(80),buyerPo:text(80),colour:text(80),sizeBreakdown:text(1000),totalQty:z.coerce.number().int().positive(),exFactoryDate:date,destination:text()}).strict(),fields:[f('styleRef','Style reference'),f('buyerPo','Buyer PO'),f('colour','Colour'),f('sizeBreakdown','Size quantities','textarea'),f('totalQty','Total quantity','number',{unit:'PCS'}),f('exFactoryDate','Ex-factory date','date'),f('destination','Destination')]},
    marker_plan:{label:'Marker and lay plan',prefix:'GM/MK/',schema:z.object({styleRef:text(80),markerNo:text(50),fabricWidthCm:pos,sizes:text(200),markerLengthMetres:pos,efficiencyPct:nonneg.max(100),plannedLays:z.coerce.number().int().positive(),plannedPly:z.coerce.number().int().positive()}).strict(),fields:[f('styleRef','Style reference'),f('markerNo','Marker number'),f('fabricWidthCm','Fabric width','number',{unit:'CM'}),f('sizes','Sizes'),f('markerLengthMetres','Marker length','number',{unit:'MTR'}),f('efficiencyPct','Marker efficiency','number',{unit:'%'}),f('plannedLays','Planned lays','number'),f('plannedPly','Ply per lay','number')]},
    bundle:{label:'Cut bundle tracking',prefix:'GM/BU/',schema:z.object({cuttingRef:text(80),bundleNo:text(50),styleRef:text(80),colour:text(80),size:text(30),pieces:z.coerce.number().int().positive(),fromSerial:z.coerce.number().int().positive(),toSerial:z.coerce.number().int().positive(),nextOperation:text(80)}).strict().refine(v=>v.toSerial-v.fromSerial+1===v.pieces,'serial range must equal bundle pieces'),fields:[f('cuttingRef','Cutting order'),f('bundleNo','Bundle number'),f('styleRef','Style reference'),f('colour','Colour'),f('size','Size'),f('pieces','Pieces','number',{unit:'PCS'}),f('fromSerial','Serial from','number'),f('toSerial','Serial to','number'),f('nextOperation','Next operation')]},
    subcontract:{label:'Subcontract operation',prefix:'GM/SC/',schema:z.object({styleRef:text(80),vendor:text(),operation:text(80),issueQty:z.coerce.number().int().positive(),ratePerPiece:pos,issueDate:date,dueDate:date,challanRef:text(80)}).strict(),fields:[f('styleRef','Style reference'),f('vendor','Subcontractor'),f('operation','Operation'),f('issueQty','Issue quantity','number',{unit:'PCS'}),f('ratePerPiece','Rate','number',{unit:'₹/PCS'}),f('issueDate','Issue date','date'),f('dueDate','Due date','date'),f('challanRef','Challan reference')]},
    quality_inspection:{label:'Garment quality inspection',prefix:'GM/QI/',schema:z.object({styleRef:text(80),inspectionStage:z.enum(['inline','endline','finishing','final']),lotQty:z.coerce.number().int().positive(),sampleQty:z.coerce.number().int().positive(),majorDefects:z.coerce.number().int().nonnegative(),minorDefects:z.coerce.number().int().nonnegative(),result:z.enum(['pass','rework','fail']),inspector:text(100)}).strict().refine(v=>v.sampleQty<=v.lotQty,'sample cannot exceed lot quantity'),fields:[f('styleRef','Style reference'),f('inspectionStage','Inspection stage','select',{options:['inline','endline','finishing','final']}),f('lotQty','Lot quantity','number',{unit:'PCS'}),f('sampleQty','Sample quantity','number',{unit:'PCS'}),f('majorDefects','Major defects','number'),f('minorDefects','Minor defects','number'),f('result','Result','select',{options:['pass','rework','fail']}),f('inspector','Inspector')]},
    final_costing:{label:'Garment final costing',prefix:'GM/FC/',schema:z.object({styleRef:text(80),producedQty:z.coerce.number().int().positive(),fabricCost:nonneg,trimCost:nonneg,labourCost:nonneg,subcontractCost:nonneg,overheadCost:nonneg,freightCost:nonneg}).strict(),fields:[f('styleRef','Style reference'),f('producedQty','Produced quantity','number',{unit:'PCS'}),f('fabricCost','Fabric cost','number',{unit:'₹'}),f('trimCost','Trim cost','number',{unit:'₹'}),f('labourCost','Labour cost','number',{unit:'₹'}),f('subcontractCost','Subcontract cost','number',{unit:'₹'}),f('overheadCost','Overhead cost','number',{unit:'₹'}),f('freightCost','Freight cost','number',{unit:'₹'})]}
  }
};

const REQUIRED:Record<string,string[]>={weaving:['write:store'],dyeing:['write:store'],exports:['write:sales'],logistics:['write:store','write:sales'],garments:['write:store']};
export const EDITION_RESOURCE_TYPES:Record<z.infer<typeof edition>,string[]>={
  weaving:['yarn','beam','loom','sizing_material','woven_fabric'],
  dyeing:['dye','chemical','recipe','machine','grey_fabric','finished_fabric'],
  exports:['export_product','packing_material','container_slot'],
  logistics:['vehicle','trailer','route','fuel','spare','handling_material'],
  garments:['fabric','trim','accessory','marker','bundle','machine','production_line','finished_garment']
};
const lineKind=z.enum(['receipt','produce','return_in','issue','consume','return_out','labour','machine','freight','duty','overhead','subcontract','other']);
const lineInput=z.object({resourceId:uuid.nullish(),lineKind,description:text(240),quantity:z.coerce.number().finite().nonnegative().max(999999999999),uom:z.string().trim().max(12).default(''),ratePaise:z.coerce.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER).default(0),amountPaise:z.coerce.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER).optional(),payload:z.record(z.string(),z.unknown()).default({})});
function canEdit(req:Request,e:string){return REQUIRED[e]!.some(p=>req.session?.permissions?.includes(p as Permission));}
function fyLabel(d:string){const y=Number(d.slice(0,4)),m=Number(d.slice(5,7));const start=m>=4?y:y-1;return`${start}-${String(start+1).slice(2)}`;}
async function nextNumber(db:Db,tenantId:string,key:string,fy:string,prefix:string){const row=await one<{prefix:string;next_number:number}>(db,`insert into document_series(tenant_id,doc_type,fy_label,prefix,next_number) values($1,$2,$3,$4,2) on conflict(tenant_id,doc_type,fy_label) do update set next_number=document_series.next_number+1 returning document_series.prefix,document_series.next_number-1 as next_number`,[tenantId,key,fy,`${prefix}${fy.slice(2)}/`]);if(!row)throw new Error('could not allocate edition document number');return`${row.prefix}${row.next_number}`;}
async function enabled(db:Db,e:string){return Boolean(await one(db,'select true as ok from tenant_edition where edition=$1 and is_enabled',[e]));}

export function editionRouter(){const r=Router();
  r.get('/editions/catalog',(_req,res)=>res.json(Object.entries(EDITION_WORKFLOWS).map(([key,workflows])=>({key,label:key[0]!.toUpperCase()+key.slice(1),resourceTypes:EDITION_RESOURCE_TYPES[key as z.infer<typeof edition>],workflows:Object.entries(workflows).map(([type,w])=>({type,label:w.label,fields:w.fields}))}))));
  r.get('/editions',async(req,res,next)=>{try{const{tenantId,userId}=req.session!;res.json(await withTenant(tenantId,userId,db=>many(db,`select e.edition,e.is_enabled,e.config,e.updated_at,count(d.id)::int as documents,count(d.id) filter(where d.status='in_progress')::int as in_progress from tenant_edition e left join edition_document d on d.edition=e.edition group by e.tenant_id,e.edition order by e.edition`)));}catch(e){next(e);}});
  r.post('/editions/config',requireWrite('owner'),async(req,res,next)=>{try{const body=z.object({edition,isEnabled:z.boolean(),config:z.record(z.string(),z.unknown()).default({})}).parse(req.body);const approvals=body.config.approvalWorkflows??[];if(!Array.isArray(approvals)||approvals.some(value=>typeof value!=='string'||!EDITION_WORKFLOWS[body.edition][value]))throw new Error('approval workflows must name workflows from this edition');const{tenantId,userId}=req.session!;const row=await withTenant(tenantId,userId,db=>one(db,`insert into tenant_edition(tenant_id,edition,is_enabled,config,activated_by) values($1,$2,$3,$4,$5) on conflict(tenant_id,edition) do update set is_enabled=excluded.is_enabled,config=excluded.config,activated_by=excluded.activated_by,updated_at=now() returning edition,is_enabled,config,updated_at`,[tenantId,body.edition,body.isEnabled,JSON.stringify(body.config),userId]));res.json(row);}catch(e){next(e);}});
  r.get('/editions/:edition/resources',async(req,res,next)=>{try{const e=edition.parse(req.params.edition);const q=z.object({resourceType:z.string().max(40).optional(),q:z.string().max(100).optional(),includeInactive:z.coerce.boolean().default(false)}).parse(req.query);const{tenantId,userId}=req.session!;const rows=await withTenant(tenantId,userId,db=>many(db,`select r.id,r.edition,r.resource_type,r.code,r.name,r.uom,r.opening_qty,r.opening_value_paise,r.payload,r.is_active,r.updated_at,s.quantity,s.value_paise,s.average_rate_paise from edition_resource r join v_edition_stock s on s.resource_id=r.id where r.edition=$1 and ($2::text is null or r.resource_type=$2) and ($3::text is null or r.code ilike '%'||$3||'%' or r.name ilike '%'||$3||'%') and ($4 or r.is_active) order by r.resource_type,r.code`,[e,q.resourceType??null,q.q??null,q.includeInactive]));res.json(rows);}catch(error){next(error);}});
  r.post('/editions/:edition/resources',async(req,res,next)=>{try{const e=edition.parse(req.params.edition);if(!canEdit(req,e))return res.status(403).json({error:`this profile cannot write the ${e} edition`});const body=z.object({id:uuid.optional(),resourceType:z.string().regex(/^[a-z][a-z0-9_]{1,39}$/),code:z.string().trim().regex(/^[A-Za-z0-9][A-Za-z0-9_.\/-]{0,39}$/),name:text(160),uom:text(12),openingQty:z.coerce.number().finite().nonnegative().max(999999999999).default(0),openingValue:z.coerce.number().finite().nonnegative().max(999999999999).default(0),payload:z.record(z.string(),z.unknown()).default({}),isActive:z.boolean().default(true)}).parse(req.body);if(!EDITION_RESOURCE_TYPES[e].includes(body.resourceType))throw new Error(`unknown ${e} resource type`);if(body.openingQty===0&&body.openingValue!==0)throw new Error('an opening value requires an opening quantity');const valuePaise=Math.round(body.openingValue*100);if(!Number.isSafeInteger(valuePaise))throw new Error('opening value is too large');const{tenantId,userId}=req.session!;const row=await withTenant(tenantId,userId,async db=>{if(!await enabled(db,e))throw new Error(`${e} edition is disabled for this company`);if(body.id&&await one(db,'select 1 from edition_stock_movement where resource_id=$1 limit 1',[body.id])){const current=await one<any>(db,'select opening_qty,opening_value_paise from edition_resource where id=$1',[body.id]);if(current&&(Number(current.opening_qty)!==body.openingQty||current.opening_value_paise!==valuePaise))throw new Error('opening quantity and value are locked after the first stock movement');}const saved=body.id?await one(db,`update edition_resource set resource_type=$2,code=$3,name=$4,uom=$5,opening_qty=$6,opening_value_paise=$7,payload=$8,is_active=$9,updated_by=$10,updated_at=now() where id=$1 and edition=$11 returning *`,[body.id,body.resourceType,body.code,body.name,body.uom,body.openingQty,valuePaise,JSON.stringify(body.payload),body.isActive,userId,e]):await one(db,`insert into edition_resource(tenant_id,edition,resource_type,code,name,uom,opening_qty,opening_value_paise,payload,is_active,created_by,updated_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11) returning *`,[tenantId,e,body.resourceType,body.code,body.name,body.uom,body.openingQty,valuePaise,JSON.stringify(body.payload),body.isActive,userId]);if(!saved)throw new Error('edition resource not found');return saved;});res.status(body.id?200:201).json(row);}catch(error){next(error);}});
  r.get('/editions/:edition/documents',async(req,res,next)=>{try{const e=edition.parse(req.params.edition);const q=z.object({docType:z.string().max(50).optional(),q:z.string().max(100).optional(),limit:z.coerce.number().int().min(1).max(500).default(100),offset:z.coerce.number().int().min(0).default(0),format:z.enum(['json','csv']).default('json')}).parse(req.query);const{tenantId,userId}=req.session!;const out=await withTenant(tenantId,userId,async db=>{const params:any[]=[e];const clauses=['d.edition=$1'];if(q.docType){params.push(q.docType);clauses.push(`d.doc_type=$${params.length}`);}if(q.q){params.push(`%${q.q}%`);clauses.push(`(d.doc_no ilike $${params.length} or d.payload::text ilike $${params.length} or d.remarks ilike $${params.length})`);}const count=await one<{n:number}>(db,`select count(*)::int n from edition_document d where ${clauses.join(' and ')}`,params);params.push(q.format==='csv'?5000:q.limit,q.format==='csv'?0:q.offset);const rows=await many<any>(db,`select d.id,d.edition,d.doc_type,d.doc_no,d.doc_date,d.status,d.approval_status,d.submitted_by,d.payload,d.remarks,d.parent_document_id,p.doc_no parent_document_no,d.created_at,l.name as party,bl.name as location from edition_document d left join edition_document p on p.id=d.parent_document_id left join ledger_account l on l.id=d.party_id left join business_location bl on bl.id=d.business_location_id where ${clauses.join(' and ')} order by d.doc_date desc,d.id desc limit $${params.length-1} offset $${params.length}`,params);return{rows,total:count?.n??0,limit:q.limit,offset:q.offset};});if(q.format==='csv')return sendCsv(res,`${e}-edition`,out.rows.map(({payload,...row}:any)=>({...row,...payload})));res.json(out);}catch(error){next(error);}});
  r.get('/editions/:edition/documents/:id',async(req,res,next)=>{try{const e=edition.parse(req.params.edition),id=uuid.parse(req.params.id);const{tenantId,userId}=req.session!;const out=await withTenant(tenantId,userId,async db=>{const document=await one(db,'select * from edition_document where id=$1 and edition=$2',[id,e]);if(!document)throw new Error('edition document not found');const events=await many(db,`select event,from_status,to_status,details,occurred_at,u.full_name as actor from edition_document_event x join app_user u on u.id=x.actor_id where document_id=$1 order by x.id`,[id]);return{document,events};});res.json(out);}catch(error){next(error);}});
  r.get('/editions/:edition/documents/:id/lines',async(req,res,next)=>{try{const e=edition.parse(req.params.edition),id=uuid.parse(req.params.id);const{tenantId,userId}=req.session!;const out=await withTenant(tenantId,userId,async db=>{if(!await one(db,'select id from edition_document where id=$1 and edition=$2',[id,e]))throw new Error('edition document not found');const lines=await many(db,`select l.id,l.resource_id,l.line_kind,l.description,l.quantity,l.uom,l.rate_paise,l.amount_paise,l.payload,r.code resource_code,r.name resource_name from edition_document_line l left join edition_resource r on r.id=l.resource_id where l.document_id=$1 order by l.created_at,l.id`,[id]);const costing=await one(db,'select * from v_edition_job_cost where document_id=$1',[id]);return{lines,costing};});res.json(out);}catch(error){next(error);}});
  r.post('/editions/:edition/documents/:id/lines',async(req,res,next)=>{try{const e=edition.parse(req.params.edition),id=uuid.parse(req.params.id);if(!canEdit(req,e))return res.status(403).json({error:`this profile cannot write the ${e} edition`});const body=z.object({lines:z.array(lineInput).max(200)}).parse(req.body);const normalized=body.lines.map(line=>{const stock=['receipt','produce','return_in','issue','consume','return_out'].includes(line.lineKind);if(stock&&(!line.resourceId||line.quantity<=0))throw new Error('stock lines require a resource and positive quantity');const amount=line.amountPaise??Math.round(line.quantity*line.ratePaise);if(!Number.isSafeInteger(amount))throw new Error('line amount is too large');return{...line,amountPaise:amount};});const{tenantId,userId}=req.session!;await withTenant(tenantId,userId,async db=>{const current=await one<any>(db,'select status from edition_document where id=$1 and edition=$2 for update',[id,e]);if(!current)throw new Error('edition document not found');if(!['draft','in_progress'].includes(current.status))throw new Error('cost and stock lines are locked after completion or cancellation');const before=await many(db,'select line_kind,description,quantity,amount_paise from edition_document_line where document_id=$1 order by id',[id]);await db.query('delete from edition_document_line where document_id=$1',[id]);for(const line of normalized)await db.query(`insert into edition_document_line(tenant_id,document_id,resource_id,line_kind,description,quantity,uom,rate_paise,amount_paise,payload,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[tenantId,id,line.resourceId??null,line.lineKind,line.description,line.quantity,line.uom,line.ratePaise,line.amountPaise,JSON.stringify(line.payload),userId]);await db.query(`insert into edition_document_event(tenant_id,document_id,event,from_status,to_status,details,actor_id) values($1,$2,'lines_replaced',$3,$3,$4,$5)`,[tenantId,id,current.status,JSON.stringify({before,lines:normalized.length}),userId]);});res.json({saved:normalized.length});}catch(error){next(error);}});
  r.post('/editions/:edition/documents',async(req,res,next)=>{try{const e=edition.parse(req.params.edition);if(!canEdit(req,e))return res.status(403).json({error:`this profile cannot write the ${e} edition`});const body=z.object({docType:z.string().min(2).max(50),docDate:date,partyId:uuid.nullish(),locationId:uuid.nullish(),parentDocumentId:uuid.nullish(),payload:z.record(z.string(),z.unknown()),remarks:z.string().max(1000).default('')}).parse(req.body);const workflow=EDITION_WORKFLOWS[e][body.docType];if(!workflow)throw new Error(`unknown ${e} document type`);const payload=workflow.schema.parse(body.payload);const{tenantId,userId}=req.session!;const row=await withTenant(tenantId,userId,async db=>{if(!await enabled(db,e))throw new Error(`${e} edition is disabled for this company`);const fy=fyLabel(body.docDate);if(!await one(db,`select 1 as ok from financial_year where label=$1 and status='open' and $2::date between starts_on and ends_on`,[fy,body.docDate]))throw new Error('document date must be in an open financial year');if(body.parentDocumentId&&!await one(db,'select 1 from edition_document where id=$1',[body.parentDocumentId]))throw new Error('linked edition document not found');const settings=await one<any>(db,'select config from tenant_edition where edition=$1',[e]);const approvalStatus=Array.isArray(settings?.config?.approvalWorkflows)&&settings.config.approvalWorkflows.includes(body.docType)?'not_submitted':'not_required';const no=await nextNumber(db,tenantId,`edition_${e}_${body.docType}`,fy,workflow.prefix);const doc=await one<any>(db,`insert into edition_document(tenant_id,edition,doc_type,doc_no,doc_date,party_id,business_location_id,parent_document_id,approval_status,payload,remarks,created_by,updated_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12) returning id,doc_no,status,approval_status`,[tenantId,e,body.docType,no,body.docDate,body.partyId??null,body.locationId??req.session?.activeLocationId??null,body.parentDocumentId??null,approvalStatus,JSON.stringify(payload),body.remarks,userId]);await db.query(`insert into edition_document_event(tenant_id,document_id,event,to_status,details,actor_id) values($1,$2,'created','draft',$3,$4)`,[tenantId,doc!.id,JSON.stringify({documentType:body.docType,parentDocumentId:body.parentDocumentId??null,approvalStatus}),userId]);return doc;});res.status(201).json(row);}catch(error){next(error);}});
  r.post('/editions/:edition/documents/:id',async(req,res,next)=>{try{const e=edition.parse(req.params.edition),id=uuid.parse(req.params.id);if(!canEdit(req,e))return res.status(403).json({error:`this profile cannot write the ${e} edition`});const body=z.object({payload:z.record(z.string(),z.unknown()),remarks:z.string().max(1000).default('')}).parse(req.body);const{tenantId,userId}=req.session!;const row=await withTenant(tenantId,userId,async db=>{const current=await one<any>(db,`select doc_type,status,payload,remarks from edition_document where id=$1 and edition=$2 for update`,[id,e]);if(!current)throw new Error('edition document not found');if(!['draft','in_progress'].includes(current.status))throw new Error('only a draft or active document can be edited');const payload=EDITION_WORKFLOWS[e][current.doc_type]!.schema.parse(body.payload);const saved=await one(db,`update edition_document set payload=$2,remarks=$3,updated_by=$4,updated_at=now() where id=$1 returning id,doc_no,status`,[id,JSON.stringify(payload),body.remarks,userId]);await db.query(`insert into edition_document_event(tenant_id,document_id,event,from_status,to_status,details,actor_id) values($1,$2,'edited',$3,$3,$4,$5)`,[tenantId,id,current.status,JSON.stringify({before:current.payload}),userId]);return saved;});res.json(row);}catch(error){next(error);}});
  r.post('/editions/:edition/documents/:id/approval/submit',async(req,res,next)=>{try{const e=edition.parse(req.params.edition),id=uuid.parse(req.params.id);if(!canEdit(req,e))return res.status(403).json({error:`this profile cannot write the ${e} edition`});const{tenantId,userId}=req.session!;const row=await withTenant(tenantId,userId,async db=>{const current=await one<any>(db,'select status,approval_status from edition_document where id=$1 and edition=$2 for update',[id,e]);if(!current)throw new Error('edition document not found');if(current.status!=='in_progress')throw new Error('only an active edition document can be submitted for approval');if(!['not_submitted','rejected'].includes(current.approval_status))throw new Error('edition document is not waiting for submission');const saved=await one(db,`update edition_document set approval_status='pending',submitted_by=$2,submitted_at=now(),approval_actor_id=null,approval_at=null,approval_reason=null,updated_by=$2,updated_at=now() where id=$1 returning id,doc_no,status,approval_status`,[id,userId]);await db.query(`insert into edition_document_event(tenant_id,document_id,event,from_status,to_status,details,actor_id) values($1,$2,'approval_submitted',$3,$3,'{}',$4)`,[tenantId,id,current.status,userId]);return saved;});res.json(row);}catch(error){next(error);}});
  r.post('/editions/:edition/documents/:id/approval/decision',requireWrite('owner'),async(req,res,next)=>{try{const e=edition.parse(req.params.edition),id=uuid.parse(req.params.id);const body=z.object({decision:z.enum(['approved','rejected']),reason:z.string().trim().max(500).default('')}).parse(req.body);if(body.decision==='rejected'&&body.reason.length<3)throw new Error('rejection requires a clear reason');const{tenantId,userId}=req.session!;const row=await withTenant(tenantId,userId,async db=>{const current=await one<any>(db,'select status,approval_status,submitted_by from edition_document where id=$1 and edition=$2 for update',[id,e]);if(!current)throw new Error('edition document not found');if(current.approval_status!=='pending')throw new Error('edition document is not pending approval');if(current.submitted_by===userId)throw new Error('the maker cannot approve their own edition document');const saved=await one(db,`update edition_document set approval_status=$2,approval_actor_id=$3,approval_at=now(),approval_reason=$4,status=case when $2='rejected' and status='in_progress' then 'held' else status end,updated_by=$3,updated_at=now() where id=$1 returning id,doc_no,status,approval_status`,[id,body.decision,userId,body.reason||null]);await db.query(`insert into edition_document_event(tenant_id,document_id,event,from_status,to_status,details,actor_id) values($1,$2,'approval_decided',$3,$4,$5,$6)`,[tenantId,id,current.status,(saved as any)?.status,JSON.stringify({decision:body.decision,reason:body.reason}),userId]);return saved;});res.json(row);}catch(error){next(error);}});
  r.post('/editions/:edition/documents/:id/status',async(req,res,next)=>{try{const e=edition.parse(req.params.edition),id=uuid.parse(req.params.id);if(!canEdit(req,e))return res.status(403).json({error:`this profile cannot write the ${e} edition`});const body=z.object({status:z.enum(['in_progress','held','completed','cancelled']),reason:z.string().trim().max(500).default('')}).parse(req.body);if(body.status==='cancelled'&&body.reason.length<3)throw new Error('cancellation requires a clear reason');const{tenantId,userId}=req.session!;const row=await withTenant(tenantId,userId,async db=>{const current=await one<any>(db,'select status from edition_document where id=$1 and edition=$2 for update',[id,e]);if(!current)throw new Error('edition document not found');const saved=await one(db,`update edition_document set status=$2::text,updated_by=$3::uuid,updated_at=now(),completed_by=case when $2::text='completed' then $3::uuid else null end,completed_at=case when $2::text='completed' then now() else null end,cancelled_by=case when $2::text='cancelled' then $3::uuid else null end,cancelled_at=case when $2::text='cancelled' then now() else null end,cancellation_reason=case when $2::text='cancelled' then $4::text else null end where id=$1 returning id,doc_no,status`,[id,body.status,userId,body.reason||null]);await db.query(`insert into edition_document_event(tenant_id,document_id,event,from_status,to_status,details,actor_id) values($1,$2,'status_changed',$3,$4,$5,$6)`,[tenantId,id,current.status,body.status,JSON.stringify({reason:body.reason}),userId]);return saved;});res.json(row);}catch(error){next(error);}});
  return r;
}
